on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  go:
    runs-on: ubuntu-latest
    name: Go ${{ matrix.go }} build
    steps:
      - uses: actions/checkout@master
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - run: go vet ./...
      - run: |
          output=$(go fmt ./...)
          if [[ ! "$output" = "" ]]; then
            printf "The following files are not go formatted:\n%s\n" "$output"
            exit 1
          fi
      - run: go test ./...
